### ISSUE TITLE
Device Type not listed on Discovery

### ISSUE THREAD

**Issue by cap60552** [jor3l/broadlinkrm-ifttt#10]
If you have multiple devices it would be helpful to have the device type listed on the discovery output.

**Comment by cap60552** [comment]
I was able to modify line 37 of device.js to accomplish this.

  console.log(`Discovered Broadlink RM device ${device.type} at ${device.host.ad
dress} (${device.host.macAddress})`)

**Comment by snobordir** [comment]
Oh nice @cap60552. I think I'll put this in my code.

**Comment by snobordir** [comment]
I just tried this and got "RM2" for both my RM Pro+ and my RM3 Mini, for what it's worth.

**Comment by jor3l** [comment]
I'll update this tomorrow, thanks
