### ISSUE TITLE
Run BroadlinkServer inside my actual node server, is it possible?

### ISSUE THREAD

**Issue by cpvbruno** [jor3l/broadlinkrm-ifttt#12]

**Comment by jor3l** [comment]
Sure, just run the code and make sure to use a different port

**Comment by cpvbruno** [comment]
I would like to use the same port, because Im already using pagekite(alternative to ngrok) to run my server, is it possible?

**Comment by jor3l** [comment]
it might be but you have to use this code and merge it into your server code

**Comment by jor3l** [comment]
instead of creating a new express (index.js file), create a Router and append that to your actual server.

**Comment by cpvbruno** [comment]
Great idea

**Comment by jor3l** [comment]
Let me know if anything else

**Comment by cpvbruno** [comment]
@jor3l worked fine for me, simple solution lol Thanks

**Comment by jor3l** [comment]
glad it worked, enjoy
