### ISSUE TITLE
Problem running npm install broadlink-rm-server

### ISSUE THREAD

**Issue by sonnysj** [jor3l/broadlinkrm-ifttt#13]
The problem occurs when running npm install broadlink-rm-server.

[root@broadlink home]# npm install broadlink-rm-server
npm http GET https://registry.npmjs.org/broadlink-rm-server
npm http GET https://registry.npmjs.org/broadlink-rm-server
npm http GET https://registry.npmjs.org/broadlink-rm-server
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-696.20.1.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "broadlink-rm-server"
npm ERR! cwd /home
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/npm-debug.log
npm ERR! not ok code 0

Can anyone fix this problem?

**Comment by jor3l** [comment]
Usually thats a problem with your network-proxy. Check that or try using a different network and see if the problem is solved. More info here: https://stackoverflow.com/questions/21855035/ssl-error-cert-untrusted-while-using-npm-command
