### ISSUE TITLE
Unable to send command

### ISSUE THREAD

**Issue by xomnia** [jor3l/broadlinkrm-ifttt#17]
I have set up the server and learned a command successfully, however when I try to run my ifttt applet, it fails on a 404 error and says command not found: acpower (acpower is the name of my command).  I am thinking maybe there is something wrong with my array formatting but not sure...my ngrok is working correctly and I am able to access from the ngrok address.  This is my commands.js with the secret removed:

module.exports = [

{

"command": "acpower",
"secret": "removed",
"mac": "77:0f:78:00:60:bf",
"ip": false,
"data": "26006000000127901411141014111436141014111411141014361411143514111436140005480001274715000c540001254714000c550001244715000d050000000000000000"

}

];

**Comment by xomnia** [comment]
Apologies, after adding a bunch of console outputs I realized that I hadn't copied the last character in my secret to IFTTT.  Doh!

**Comment by jor3l** [comment]
Lol, glad you got that working. Have fun
