### ISSUE TITLE
Learning Time Out

### ISSUE THREAD

**Issue by krishna383** [jor3l/broadlinkrm-ifttt#18]
Hi I just started my broadlink server with learning mode. But unfortunately when I hit the URL, it is timing out

![image](https://user-images.githubusercontent.com/12377285/39973480-f1667eee-56e5-11e8-8b1e-9f235f1bdd38.png)

![image](https://user-images.githubusercontent.com/12377285/39973477-ea68d682-56e5-11e8-810a-e435536440fc.png)

I am using a RM Mini 3

**Comment by jor3l** [comment]
Are you pointing the remote and trying a key?. How long until the timeout occurs?

**Comment by jor3l** [comment]
I'm closing this, reopen if needed. Cheers
