### ISSUE TITLE
 Error: Cannot find module 'broadlink-rm-server'

### ISSUE THREAD

**Issue by jeffl78** [jor3l/broadlinkrm-ifttt#19]
I installed ngrok and broadlink-rm-server 
via npm and was able to follow all the instructions without issue, from what I can tell, up until I run “node index” in the command prompt.  At that point, I get an error saying broadlink-rm-server cannot b found.  Following the steps on Ngrok’s website the commands “./ngrok http 80” and “./ngrok help” both appear to work fine.  However, when I go to http://localhost:4040 in my browser I get an error that says tunnel was established successfully but local client failed to connect at address localhost:80.  It also says to make sure the web server is running on localhost:80 and it is a valid address.  Additionally, the error code appear as follows: “dial tcp [::1]:80: getsockopt: connection refused”.  I’m the command prompt you get an error that reads: “502 Bad Gataway”

All of the other commands after this in the project through errors and I have all the files in home/pi at this point.  Initially, I had all the files in my usr/local/lib/node_modules/homebridge file but an error occurred telling me to put both the index.js and command.js files in the home/pi folder.  After moving these files I’m getting the error bellow.  I’m running noobs raspbian on a raspberry pi 3b with jsnode v 8.11.1, homebridge v.0.4.42.  Any help would be appreciated.  Thanks in advance.

pi@raspberrypi:~ $ node index
module.js:549
    throw err;
    ^

Error: Cannot find module 'broadlink-rm-server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/index.js:4:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
pi@raspberrypi:~ $

**Comment by jeffl78** [comment]
Update: 

I uninstalled and reinstalled broadlink-rm-server and it now runs and says to browse to http://localhost:1880 but when I do so the window that opens says "can't / Get" real small in the upper left hand corner and nothing else occurs.  I am running homebridge-config-ui-x, a homebridge server but I do not think this is causing the issue I am experiencing.

**Comment by jor3l** [comment]
Hi, the error when trying to get the / root is fine, instead, try going to a command url and see if that runs your code like this: 

```
curl -X POST \
  http://localhost:1880/command/TVSound \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 0b4564c1-5ab0-431c-84dd-b4bea5e21517' \
  -d '{"secret": "AkDio83"}'
```

Make sure to replace the localhost:PORT if needed.

**Comment by jeffl78** [comment]
When you say command url do you mean command terminal?

**Comment by jor3l** [comment]
No, this is a command url: http://localhost:1880/command/TVSound. The last part (TVSound) is the name of the command defined in the command.js file

**Comment by jeffl78** [comment]
I’m sorry to keep bugging you about this, my knowledge is limited at this point but I am excited to get this server running.  I posted that link you sent to my browser after starting the server using “node index” and the message “Cannot GET /command/TV/Sound” appeared in the upper left of window.  

Right now my command.js file is still in the original state as I have not modified it at all.  I did add “true” to the index.js file to enable the IR learn feature.  Should I add a command at this point and are the secrets generated from the IR learn output?

**Comment by jor3l** [comment]
Use the commands file this repo has as an example. Btw, when you run the code does the broadlink shows up in the console?. You need to find the mac address or the IP on order to use the learning URL.

**Comment by jeffl78** [comment]
When I run node index I get the message "Server running, go to http://localhost:1880
Discovered Broadlink RM device at 192.168.0.xxx (xx:xx:xx:xxxx:xx)" with my rm pro's information.  I added this to my command.js file with my mac address substituted:
{
    command: "Projector",
    secret: "dnja9kdtn",
    mac: "34:ea:34:bb:16:1a",
    ip: true,
    data:"260058000001289413121213111413121213111413121114113911391238113911391238111412381114123811141213111411141212121410391214103912391237113912391237110005490001264b12000c5e0001264b11000d05"
}

I wanted to mention that I have not set up my webhooks yet, though I have an account and have used webhooks before so do not see that being an issue.  From what I can tell webhooks won't be needed until after I get the server running and some commands successfully executed but wanted to be sure. 

So now I want to run node index and then past the command you mentioned earlier into my browser correct?  Do I just change the names and the secrets match or am I still not understanding something?

I am referring to this url that you sent:

curl -X POST \
  http://localhost:1880/command/TVSound \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{"secret": "AkDio83"}'

Once again, sorry to bother you with this, your assistance is much appreciated.

**Comment by jor3l** [comment]
The OK is the default since the server responds with a status 200, your RM should play the IR command after that, did you get it working?

**Comment by jeffl78** [comment]
I have not had much time lately and am just now getting back to this project now. I believe I left it in a good spot though. Thank you for asking though, actually I was staring at the config today wondering if there is a way to send repeat requests and if so can you change the delay between requests.  It may be explained in the old issues or even right on the readme page, I have not looked extensively yet so it may be that I just have not come across it yet.

**Comment by jor3l** [comment]
Maybe the sequence works for you, without the delay tho. Anyways let me know if you get this up and working

**Comment by jor3l** [comment]
Let me know if need help, closing this for now
