### ISSUE TITLE
Sending RF Command

### ISSUE THREAD

**Issue by Hujairi** [jor3l/broadlinkrm-ifttt#2]
it all works fine but am trying to configure an RF command for my tc2 switch i won't work, code tested using the android rm bridge it worked fine but i didn't work in the server.

IR codes works fine, RF codes received with 200 ok status but no action from the broadlink.

**Comment by Hujairi** [comment]
example
IR code: "26008c004d14281313142615131425151414121527131413131413151200034b4e14261512152614131526141314131427141314131413141300034b4d14261514132615121526141314131526141314131413141300034b4d15271313142714131426151215141326151215131413141200034b4f132813131427141215261413141413271414131314131414000d05000000000000000000000000" it worked just fine.

but TC2 Gang switch RF code: "e9144600df091609091609161609091609161609160909161609160916090916160909161609091609161609160909161609160909161609160909160916091616091609160909000148" won't work at all, some said to double it up twice , i tried it didn't worked.
codes retrieved by RM "tasker" Plugin. i tried thru the rm bridge and it worked : 
http://192.168.1.39:7474/?cmd=%7B%22api_id%22:1004,%22command%22:%22send_code%22,%22mac%22:%22xx:xx:xx:xx:xx:xx%22,%22data%22:%22e9144600df091609091609161609091609161609160909161609160916090916160909161609091609161609160909161609160909161609160909160916091616091609160909000148%22%7D

**Comment by jor3l** [comment]
Hi, did you get it working?

**Comment by Hujairi** [comment]
Unfortunately, no i've been trying but none of the solution in the internet worked .

**Comment by jor3l** [comment]
I'm getting one soon, hopefully we can get that working.

**Comment by jor3l** [comment]
BTW, checkout home-assistant.io.

**Comment by jor3l** [comment]
As of today, I'll be getting some GE switches so I can't really test this. Maybe someone that has this switch could help here, for now I'm closing this issue. Cheers!
