### ISSUE TITLE
Problem running npm install broadlink-rm-server

### ISSUE THREAD

**Issue by Malzmeier** [jor3l/broadlinkrm-ifttt#20]
I tried to set up a new pi and again use the node script to control my rm mini as on my old pi. 
But at start i ran into the following error. I use Raspbian Stretch.

pi@raspberrypi:~ $ npm install broadlink-rm-server
(node:2692) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node_modules/broadlink-rm-server/node_modules/lodash'
npm ERR! error rolling back  broadlink-rm-server@0.0.6 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node_modules/broadlink-rm-server/node_modules/lodash'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/node_modules/broadlink-rm-server/node_modules/lodash' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.71-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "broadlink-rm-server"
npm ERR! cwd /home/pi
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! tar.unpack untar error /home/pi/.npm/vary/1.1.2/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node_modules/broadlink-rm-server/node_modules/helmet/node_modules/helmet-csp/lib/check-options'
npm ERR! error rolling back  helmet@3.15.0 { Error: ENOTEMPTY: directory not empty, rmdir '/home/pi/node_modules/broadlink-rm-server/node_modules/helmet/node_modules/helmet-csp/lib/check-options'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/node_modules/broadlink-rm-server/node_modules/helmet/node_modules/helmet-csp/lib/check-options' }
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0

**Comment by jor3l** [comment]
I need to update lodash to the latest version, will do so now, thanks for letting me know and sorry for the late response
