### ISSUE TITLE
Unable to learn RF commands

### ISSUE THREAD

**Issue by twittwer** [jor3l/broadlinkrm-ifttt#25]
Hi,
IR works great, thx 👍 

But I have some trouble with the RF commands. I saw there were already some issues, but they seem unresolved.

Is there some kind of instruction about how to work with RF remotes or is it not possible.

Thx for any help 🙏

**Comment by jor3l** [comment]
Hey, what kind of problems are you having?

**Comment by twittwer** [comment]
I got a timeout every time I tried to learn a RF command. I got it working with another library ([broadlink-mqtt-bridge](https://github.com/fbacker/broadlink-mqtt-bridge)) and it seems like the RF learning requires 2 steps. At first, it analyses the frequency (RF Sweep) and secondly it records the actual code.
