### ISSUE TITLE
RM Bridge web interface Code Learning page

### ISSUE THREAD

**Issue by mikejrh** [jor3l/broadlinkrm-ifttt#3]
using mini3 device: When I manually add MAC address, device name and RM2 in the RM Bridge web interface Code Learning page I get the "ERROR: HTTP/404"  message.  Do you have any suggestions?

**Comment by jor3l** [comment]
That website has been giving me so many problems lately, try with the IP or try to debug the Web Console and see if there is an error there

**Comment by mikejrh** [comment]
Not sure how to get the code information with the IP address.  Thanks.

Michael Flamm

**Comment by jor3l** [comment]
Did you get this working? I'm closing for now this bug
