### ISSUE TITLE
Trouble starting

### ISSUE THREAD

**Issue by abrenoch** [jor3l/broadlinkrm-ifttt#5]
Hey there, I'm trying to get this running but am having trouble getting it to run with node.

I'm getting this 'weird error 127' - which seems to indicate I need the legacy version of nodejs. So I installed that one and it does not seem to like the ECMA6 syntax very much (even using the flags to try and force support).

Any idea what I'm doing wrong? It isn't immediately obvious to me right now!

Thanks!

**Comment by abrenoch** [comment]
Here is the full output:

```
> BroadLinkServer@0.0.1 start /var/broadlinkrm-ifttt
> node server.js

sh: 1: node: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by abrenoch** [comment]
It seems like there was an issue with the version of nodejs I installed using `apt-get`. I used the tool provided here: https://github.com/creationix/nvm and everything seems to be ticking along now!

**Comment by jor3l** [comment]
Glad you got this working :)
