### ISSUE TITLE
Problem detecting my RMPRO

### ISSUE THREAD

**Issue by martyouel** [jor3l/broadlinkrm-ifttt#7]
Hi,

i'm not sure if this is still an alive project but I take my chance.
After doing a lot of research it looks like this project is exactly what I need.

My problem is that I think that my RMPRO is not detected.

I followed the instruction to install it on my Windows Server 2012.
I saw nothing about the configuration of my RMPRO (ip and/or mac) so I assume that the project use a kinf of auto-discovery ?

When I start the application :

node index

I get the answer back :

Server running, go to http://localhost:1880

When I go to the address :

Cannot GET /

I suspected first that maybe there is a firewall rule that block some trafic getting out of my server. So I add an outbound rule to do not block anything.

My server and my RMPRO are on the same network (192.168.12.XX) and from my server I can ping with no problem the RMPRO.

Is somebody can help me ?

thanks

**Comment by jor3l** [comment]
Hi @martyouel,

Cannot GET /: This is fine, the server does not expose anything on that path-method.

After the message with ```Server running, go to http://localhost:1880``` the server will try to auto discover your RM device and will output its mac address or IP when found, unfortunately I only have a RM Mini 3 and can't tell you for sure if there is a problem with the code or is just something with your setup.

For example on my Mac it doesn't find my RM but when I run the code on the Raspberry it does. Could you try to run this with another machine/OS?

**Comment by martyouel** [comment]
Hi jor3l,

ok, i'll give a try on a ubuntu desktop.

I just tried homebridge-broadlink-rm on this ubuntu workstation and it works great to interact with my RMPRO. 
So I hope that it will work with your application.

thanks

**Comment by jor3l** [comment]
Let me know, thanks!

**Comment by martyouel** [comment]
Well i think that i am near the solution.

From the ubuntu workstation when I start the application I get the message saying the RMPRO has been discovered.

Now my problem is to make the communication works.
I added a simple command to turn on my TV. 
This command has been tested and work now from homebridge-broadlink-rm.

Here's my commands.js :

module.exports = [{
        "command": "TV_On",
        "secret": "martin",
        "mac":"34:ea:34:89:13:XX",
        "data": "2600780000012791141114111436141114111411141114111435143614111435143614351436143514111411141114361411141114111411143514361435"
    }
];

By using postman on an other machine on my network I post a JSON request to :

http://serverip:1880/command/TV_On

with the secret in the body.

When I do the call I get an "OK" answer back. 

But, the problem, is that nothing is triggered on the RMPRO. I should at minimum see the light turn on on the device but it won't turn on :(

any idea ?

**Comment by jor3l** [comment]
Sorry for the late response, I have no idea, not sure if the PRO is looking for a different format and unfortunately I'm not able to test it since I have the mini, let me know if you figure out whats wrong so we can fix this code and improve it for the others
