### ISSUE TITLE
Use without ngrok

### ISSUE THREAD

**Issue by lubepi** [jor3l/broadlinkrm-ifttt#8]
When i use ngrok it works perfectly fine, but i want to send the POST request directly to my RPi without the tunnel. I granted access for incomming request on port 1880 and that works, too. I can see "Cannot GET /" like with ngrok but when i send the post request via ifttt nothing happens.

**Comment by jor3l** [comment]
You need to have the RPi exposed to the network, local IP won't work. I guess you could setup a tunnel or a DMZ with your Router

**Comment by lubepi** [comment]
It is exposed. I have granted access to all ports in my router for the RPi. I can ping, SSH, etc. and access port 1880 from the internet. That works. Only the POST request from the ifttt webhooks has no effect. And I don't know why..
