### ISSUE TITLE
Help with README instructions

### ISSUE THREAD

**Issue by rbhale** [jor3l/broadlinkrm-ifttt#9]
Hi @jor3l , I apologize that I'm coming at this somewhat blind (I'm not familiar with javascript, etc). I'm having a hard time following the README instructions. 

For example, it says to create an index.js and a commands.js, but those files both exist in this package. Should I just modify them? Then I think, the code suggested in the README to be in index.js is in example.js already. 

Also, can you offer any more specific advice about how to use the server? For learning codes? It says to go to your "server URL" in the README...which file should I be browsing to? 

Sorry for the newbie questions. Any further guidance is appreciated. Thank you!

**Comment by jor3l** [comment]
Hi! They are there in case you don't use the NPM package, if you did install this repo using npm then you are actually following the instructions since using the source is a bit different. Server URL if on the same machine is always localhost if you're running this on another computer then use that IP address. Let me know if it worked

**Comment by rbhale** [comment]
Also, when I use the command `ngrok http 1880`, I'm told "command not found." Do I need to be in a specific folder to run ngrok? Or somehow make it so it can be found anywhere?

**Comment by jor3l** [comment]
Check if the port is open, usually with `sudo ufw allow 1818`. For the ngrok, you have to download the file from ngrok.com and then run it with the command

**Comment by rbhale** [comment]
I’ll check the port next time I’m working on this, thank you. 

I installed ngrok with npm. I installed it globally, if that makes a difference. I finally got it to run by finding it in nodejs/bin and explicitly typing out ./ngrok. I’m just not sure why it won’t run anywhere with just “ngrok,” seems like installing it globally (with sudo, I believe) would land it on my path—most npm packages I install in that way are.

**Comment by jor3l** [comment]
Not sure but I think the npm package for ngrok is actually an older version, you could install the one available at the website globally too. Also, make sure to get an account so your ngrok URL doesn't change or you're able to tell when it does to update IFTTT

**Comment by rbhale** [comment]
Oooh gotcha. I'll grab it off the website and make sure ngrok is up to date. And check that the port is open. Then I'll update. Thank you for your help!

**Comment by jor3l** [comment]
Fingers crossed, let me know

**Comment by rbhale** [comment]
Ah! Eureka! I got it working. My main mistake: I was following the instructions to run `node index`, but the npm version of your code has the code mentioned as index.js in the instructions in _example.js_. Once I ran node example (and I had to be in the directory of the package), it finally worked. For some reason I still can't access the ngrok web interface. Maybe you can't access that externally? I'm doing this on a pi and don't know curl well enough to access web info from the command line. I tried to access it from my laptop. Anyway, I got a test IFTTT command to work!!

Some questions (and I can open new issues for these if you want):

1. Tips for running ngrok in the background? I can do it easy enough with `ngrok http 1880 &`, but I can't get the random URL that I have to use, since I only have a free account.

2. Will this method work for RF commands? My understanding is usually you have to do a "scan frequency" with the Broadlink Pros in order to learn RF. I know you said you've only tested this on a Mini that only does IR, so if you're not aware I'll test it out myself and let you know.

**Comment by rbhale** [comment]
Oh oops figured out #1. You can go to the ngrok website and find your URL in the Status page :)

**Comment by rbhale** [comment]
Oh another question: Have you configured this to send multiple commands at all (for example, turn up the volume 5 times)? I'm planning on using Stringify web hooks and can probably just make it work with that, but figure if it's more efficient to somehow do it within this interface maybe it's more efficient than sending the same command over and over.

**Comment by cap60552** [comment]
@rbhale have you had any luck scanning RF codes? I tried a little bit this morning but couldn't seem to get it to detect them.

**Comment by rbhale** [comment]
Net yet @cap60552. I may have some smart home playtime tonight, I’ll try to remember to give it a shot.

**Comment by jor3l** [comment]
You could use the sequence to send 5 volume up commands or turn multiple things at once

**Comment by jor3l** [comment]
For the learning, I tested my mini RM and it worked, basically you hit the learn URL, point the remote and press the button you want to record, then you get the code for that button

**Comment by snobordir** [comment]
I figured out the sequence thing, good stuff. IR learning doesn't give any issues, I think @cap60552 and I are more worried about RF devices. That can be discussed in the other issue, I think.

**Comment by jor3l** [comment]
@snobordir closing this issue then, please open another issue if need help or send a pull with improvements
